# Generated by Django 4.2.4 on 2023-08-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0003_genre_remove_book_genre_book_genr'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Страна'),
        ),
    ]
