# Generated by Django 4.2.4 on 2023-08-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0004_user_city_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True, help_text='Отметьте, если книга доступна для выдачи', verbose_name='В наличии'),
        ),
    ]
