# Generated by Django 4.2.4 on 2023-08-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0004_exchange_user_receiver_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookStatus',
        ),
    ]
