# Generated by Django 4.2.4 on 2023-08-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0006_status_bookexchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookexchange',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exchanges', to='exchange_app.status'),
        ),
    ]
