# Generated by Django 4.2.4 on 2023-08-05 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0009_exchangerequest_delete_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='exchangerequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='exchangerequest',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='exchange_app.user'),
        ),
        migrations.DeleteModel(
            name='BookExchange',
        ),
        migrations.DeleteModel(
            name='ExchangeRequest',
        ),
        migrations.AddField(
            model_name='exchange',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='exchange_app.book'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='book1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book1', to='exchange_app.book'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='exchange_app.user'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='exchange_app.user'),
        ),
    ]
