# Generated by Django 4.2.4 on 2023-08-05 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0010_exchange_remove_exchangerequest_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_exchanges', to='exchange_app.book'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='book1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book1_exchanges', to='exchange_app.book'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exchanges', to='exchange_app.user'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_exchanges', to='exchange_app.user'),
        ),
    ]
