# Generated by Django 4.2.4 on 2023-08-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0012_alter_book_user_alter_exchange_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='user1',
        ),
    ]
