# Generated by Django 4.2.4 on 2023-08-05 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange_app', '0013_remove_exchange_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='user1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user1_exchanges', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
