# Generated by Django 4.2.4 on 2023-08-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0015_exchange_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
