# Generated by Django 4.2.4 on 2023-08-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0016_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='book1',
            new_name='book_receiver',
        ),
        migrations.RenameField(
            model_name='exchange',
            old_name='book',
            new_name='book_sender',
        ),
        migrations.RenameField(
            model_name='exchange',
            old_name='user1',
            new_name='user_receiver',
        ),
        migrations.RenameField(
            model_name='exchange',
            old_name='user',
            new_name='user_sender',
        ),
    ]
