# Generated by Django 4.2.4 on 2023-08-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0017_rename_book1_exchange_book_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genr',
            new_name='genre',
        ),
    ]
