# Generated by Django 4.2.4 on 2023-08-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_image'),
        ('exchange_app', '0019_alter_exchange_user_receiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_app.condition'),
        ),
    ]
