# Generated by Django 4.2.4 on 2023-08-15 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0020_condition_alter_book_user_alter_book_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='exchange_app.condition'),
        ),
    ]
